### ISSUE TITLE
License

### ISSUE THREAD

**Issue by czipperz** [flipturnapps/FlipTurnApps-KevinLibrary#2]
Since you have no license on this project, it is implicitly copyrighted and illegal for use without explicit permission from you.  Consider adding a file LICENSE that contains a software license.

There are many different types of software licenses.  GNU and Linux use the GNU GPL, a restrictive copyleft license that seeks to empower the user, but forces all works using the library to also be GPL'd.  Many projects use the MIT or ZLib licenses, which are permissive free software licenses, allowing you to keep the coyright without restricting the rights of developers using your work.

Some licenses aren't compatible because they impose restrictions that another license doesn't allow.  For example, a project licensed under ZLib couldn't use a GPL'd library, but a GPL'd project can use a ZLib licensed library.  A way to get around this is to the use the LGPL for libraries.

I personally use Copyfree licenses, such as ZLib and MIT licenses.

https://www.wikiwand.com/en/Software_license
https://www.wikiwand.com/en/Free_software

**Comment by kkevlar** [comment]
License is now added to the master branch

**Comment by czipperz** [comment]
Since you chose the GPL, I highly recommend switching to the  GPLv3 over v2.  As I said above, the GPL requires all projects using the GPL to have the same license: the GPL. So every project using this library must be GPLd when they use any commit that has the GPL license.

**Comment by czipperz** [comment]
Even if the library or application only uses this library as a jar, it must be licensed under the GPL.

**Comment by czipperz** [comment]
This is what is referred to as the recursive or viral aspect of the GPL. It is why I use the Mozilla Public License. It yields the same rights to the user for that application, but doesn't require derivative works to be under the MPL.

**Comment by czipperz** [comment]
tldrlegal.com is a good reference website for software licenses
